module.exports = {
  lang_prompt: "🌍 Оберіть мову / Choose your language / Выберите язык",
  lang_saved: "✅ Мову збережено.",
  lang_unsupported: "Непідтримувана мова.",
  lang_save_error: "Не вдалося зберегти мову. Спробуйте пізніше.",

  cmd_start: "🏠 Головне меню",
  cmd_menu: "📋 Відкрити меню",
  cmd_book: "📅 Почати бронювання",
  cmd_language: "🌍 Змінити мову",
  cmd_admin: "👑 Адмін-панель",

  welcome_new:
    "👋 Вітаємо, {name}!\n\nЩоб продовжити, будь ласка, пройдіть коротку реєстрацію.",
  welcome_back: "👋 З поверненням, {name}!",

  enter_name: "✏️ Будь ласка, введіть ваше ім'я:",
  enter_phone:
    "📞 Будь ласка, введіть номер телефону у міжнародному форматі (наприклад, +79995551234):",
  enter_passport: "🪪 Надішліть фото паспорта або введіть номер:",

  update_name_prompt: "✏️ Введіть нове ім'я:",
  update_tel_prompt:
    "📞 Введіть номер телефону або надішліть контакт (кнопка нижче):",
  update_passport_prompt:
    "🆔 Надішліть фото паспорта або введіть його номер:",
  share_contact_btn: "📨 Надіслати контакт",

  menu_title: "🏠 Головне меню:",
  quick_book: "Бронювання",
  quick_prices: "Ціни",
  main_menu_book: "📅 Забронювати",
  main_menu_bookings: "🗂 Мої бронювання",
  menu_my_rent: "🚘 Моя оренда",
  menu_support: "💬 Підтримка",
  menu_prices: "💸 Ціни",
  prices_dynamic_hint:
    "Точна вартість розраховується за актуальними тарифами для обраної техніки та дат оренди.",
  menu_account: "👤 Мій профіль",
  menu_conditions: "📝 Умови оренди",
  menu_about: "ℹ️ Про нас",
  menu_book: "📅 Забронювати байк",
  menu_rental: "🧾 Моя оренда",
  menu_update_name: "✏️ Змінити ім'я",
  menu_update_tel: "📞 Змінити номер",
  menu_update_passport: "🪪 Завантажити паспорт",

  support_info:
    "💬 Підтримка.\nЯкщо у вас виникли питання — оберіть зручний спосіб зв'язку нижче.",
  support_btn_call: "📞 Подзвонити нам",
  support_btn_faq: "📄 FAQ",
  support_btn_find: "📍 Як нас знайти",
  support_btn_admin: "💬 Написати адміністратору",
  support_call_text:
    "📞 Телефон: +66 97 181 9946\n💬 WhatsApp: +66 97 181 9946\n\nНатисніть кнопку нижче, щоб відкрити чат у WhatsApp.",
  support_call_whatsapp_btn: "💬 Написати у WhatsApp",
  support_faq_text:
    "📄 FAQ\n\n• Як забронювати? — Оберіть дати й байк у боті, підтвердьте оренду.\n• Які документи потрібні? — Фото паспорта.\n• Чи є шоломи? — Так, видаємо на запит.\n• Доставка байка? — Доступна, уточніть адресу в коментарях.\n• Оплата? — Уточнимо під час підтвердження бронювання.",
  support_find_text:
    "📍 Адреса: Koh Phangan, Thailand\n\nНас легко знайти:\n🔗 <a href=\"https://maps.app.goo.gl/TwjvSmA6TjJuka1t8\">Google Maps</a>\n📸 <a href=\"https://www.instagram.com/drive_phangan/\">Instagram</a>\n📘 <a href=\"https://www.facebook.com/drivephangan\">Facebook</a>",
  prices_info:
    "💸 Актуальні ціни видно при виборі байка.\nНатисніть «Моя оренда», щоб обрати дати й побачити суму.",
  prices_choose_season:
    "Оберіть сезон:\n\n🔺 Високий сезон (грудень, січень, лютий, березень)\n🟠 Середній сезон (квітень, травень, жовтень, листопад)\n🔻 Низький сезон (червень, липень, серпень, вересень)",
  prices_choose_type: "Оберіть тип транспорту для перегляду тарифів.",
  prices_type_bikes: "🛵 Байки",
  prices_type_cars: "🚗 Автомобілі",
  prices_season_high: "🔺 Високий сезон",
  prices_season_middle: "🟠 Середній сезон",
  prices_season_low: "🔻 Низький сезон",
  prices_image_missing:
    "Не вдалося завантажити прайс-лист. Спробуйте ще раз.",
  prices_loading: "Завантажую прайс-лист…",
  account_info:
    "👤 Тут ви можете вказати свої дані для бронювання. Оберіть, що хочете оновити:",
  account_profile_title: "👤 Мій профіль",
  account_name_label: "Ім'я",
  account_phone_label: "Телефон",
  account_passport_label: "Паспорт",
  account_passport_photo: "Фото завантажено",
  account_passport_missing: "Не вказано",
  account_value_missing: "Не вказано",
  account_passport_number_value: "Номер: {number}",
  account_profile_hint: "Оберіть, що хочете змінити:",
  conditions_info:
    "🆔 Документи\nОбов'язково:\n• Фото закордонного паспорта\n• Водійське посвідчення (міжнародне — бажано)\n• Вік від 18 років\nПідписання договору оренди — обов'язкове.\n\n💰 Депозит та оплата\nДепозит:\n• Паспорт або грошова застава\n• Сума залежить від моделі:\n▫️ Звичайні байки — 100–300$\n▫️ Потужні байки (300–350cc) — від 400$ і вище\n\nОплата:\n• Готівкою або онлайн\n• Усі умови обговорюються заздалегідь — без прихованих платежів\n\nПовернення раніше строку:\nЯкщо плануєте повернути скутер раніше, врахуйте:\n• При подобовій оренді — повернення менш ніж за 3 дні до завершення не компенсується\n• При помісячній оренді — повернення менш ніж за 7 днів також не перераховується\n• В інших випадках можливий перерахунок за домовленістю\n\n🛵 Пошкодження та відповідальність\nПеред орендою робимо фото та відео байка.\nУ разі пошкоджень:\n• Оплата за реальною вартістю оригінальних запчастин і робіт\n• Іноді може враховуватись простій на ремонт\nСтраховка на скутери не поширюється.\nПробите колесо орендар ремонтує самостійно — зазвичай 100–200 бат у найближчій майстерні.\nЯкщо акумулятор сів через увімкнене світло фар — сервісний збір 100–400 бат залежно від локації.\n\n⏱ Повернення та продовження\nОренда рахується на добу — повернення в той самий час, коли байк отримали.\nЯкщо хочете продовжити, попередьте завчасно, бажано за кілька днів.\nУ високий сезон техніка часто бронюється день-у-день — важливо дотримуватись домовленостей.\nПродовження на пів дня (наприклад, з обіду до вечора) — можливо за домовленістю, зазвичай ~50% від вартості дня.\n\n📍 Отримання транспорту\nВидача техніки — на Бан таї.\nДоставка скутера:\n• По острову — від 100 до 400 бат (залежно від відстані)\n• До пірсу Тонгсала — 150 бат\n• По Бан таю — безкоштовно",
  conditions_accept_btn: "✅ Прийняти умови оренди",
  conditions_accepted_label: "✅ Умови прийнято",
  conditions_book_btn: "📅 Забронювати",
  conditions_view_btn: "📄 Умови оренди",
  conditions_accept_required:
    "Щоб підтвердити бронювання, прийміть умови оренди. Натисніть «Прийняти умови оренди».",
  conditions_version_changed:
    "Умови оренди змінилися. Перед підтвердженням бронювання перегляньте нову версію та прийміть її.",
  conditions_terms_link:
    "Повний текст користувацької угоди можна запросити у менеджера.",

  booking_price_tbd: "ціна уточнюється",

  rent_intro: "Давайте підберемо ідеальний скутер. Оберіть дію:",
  rent_btn_book: "🚘 Забронювати",
  rent_btn_current: "🗂 Поточні бронювання",
  rent_btn_history: "📜 Історія оренд",
  rent_btn_contract: "📄 Договір оренди",
  rent_btn_payment: "💰 Депозит/Оплата",
  rent_btn_settings: "⚙️ Налаштування",
  rent_btn_support: "💬 SUPPORT",
  rent_btn_confirm: "✅ Підтвердити бронювання",
  rent_current_empty: "У вас немає активних чи очікуючих бронювань.",
  rent_current_title: "📌 Ваші поточні бронювання",
  rent_current_draft_title: "📝 Чернетка бронювання",
  rent_current_draft_hint:
    "Можна продовжити оформлення зараз або повернутися пізніше.",
  rent_current_draft_continue_btn: "Продовжити бронювання",
  rent_current_back_btn: "⬅️ До поточних бронювань",
  rent_current_actions_title: "⚙️ Керування чернеткою",
  rent_current_actions_hint:
    "Додайте байк, залиште побажання або підтвердьте бронювання перед відправкою адміну.",
  rent_history_empty: "Історія пуста.",
  rent_details_title: "📍 Деталі бронювання",
  rent_details_status: "Статус: {status}",
  rent_history_page: "Сторінка {current} / {total}",
  rent_details_category: "Категорія: {category}",
  rent_details_days: "Днів оренди: {days}",
  rent_details_created: "Створено: {created}",
  rent_details_reason: "Причина: {reason}",
  rent_status_unknown: "статус недоступний",
  rent_status_process: "у процесі",
  rent_status_pending: "очікує підтвердження",
  rent_status_active: "активна",
  rent_status_ready: "готова до видачі",
  rent_status_cancelled_by_client: "скасована клієнтом",
  rent_status_cancelled: "скасована",
  rent_status_completed: "завершена",
  rent_status_approved: "підтверджена",
  rent_status_expired: "прострочена",
  rent_status_no_show: "неявка",
  reminder_start_24h: "Нагадування: оренда починається через 24 години",
  reminder_start_1h: "Нагадування: оренда починається через 1 годину",
  reminder_end_24h: "Нагадування: оренда завершується через 24 години",
  reminder_end_1h: "Нагадування: оренда завершується через 1 годину",
  reminder_model_label: "Модель",
  reminder_period_label: "Період",
  reminder_status_label: "Статус",
  reminder_view_current_btn: "Поточні бронювання",
  reminder_view_details_btn: "Деталі бронювання",
  user_rental_approved:
    "Ваше бронювання #{id} підтверджене адміністратором ✅\nМодель: {model}\nДати: {start} — {end}\nСтатус: {status}\nДеталі можна переглянути у розділі My Rent.",
  rent_view_details_btn: "Переглянути бронь",
  rent_details_dates: "Дати: {start} - {end}",
  rent_details_model: "Модель: {model}",
  rent_details_unit: "Юніт: {unit}",
  rent_details_helmets: "Шоломи: {helmets}",
  rent_details_delivery: "Доставка: {delivery}",
  rent_details_address: "Адреса: {address}",
  rent_details_notes: "Побажання: {notes}",
  rent_details_price: "Сума: {price} THB",
  rent_details_deposit: "Депозит: {deposit} THB",
  rent_details_contract: "Договір: {contract}",
  rent_action_details: "📍 Деталі",
  rent_action_edit: "✏️ Редагувати",
  rent_action_cancel: "❌ Скасувати",
  rent_action_back: "◀️ Назад",
  rent_cancel_confirm: "Скасувати бронювання ID {id}?",
  rent_cancel_confirm_action: "Так, скасувати бронювання",
  rent_cancelled: "Бронювання скасовано.",
  rent_cannot_cancel: "Не можна скасувати це бронювання.",
  rent_cancel_manager_required:
    "До початку оренди залишилося менше 24 годин. Для скасування та уточнення передоплати зв'яжіться з менеджером напряму: {manager}",
  rent_cancel_manager_contact_missing:
    "До початку оренди залишилося менше 24 годин. Автоматичне скасування недоступне; зверніться до нас через розділ «Підтримка».",
  rent_history_details: "📍 Деталі (історія)",
  about_info:
    "🏝️ DRIVE PHANGAN — оренда скутерів та авто на острові Ко Пханган.\nОфіційно працюємо з 2019 року.\n🛵 Щороку оновлюємо парк новими моделями — для тих, хто цінує комфорт, стиль і свободу пересування.\n\n🚀 Оренда у нас — це чесно і прозоро: без мутних схем і «розводів» на подряпини.\n⭐ Понад 100 позитивних відгуків у Google Maps і багато клієнтів, які повертаються до нас сезон за сезоном.\nНадійно, просто і з турботою про ваш відпочинок ✨\n\n🤖 Цей бот створено, щоб спростити оренду: усе автоматизовано, без зайвої рутини. Ви можете пройти всі етапи бронювання прямо тут. Якщо виникнуть питання — ми на зв'язку!\n\n📍 Нас легко знайти:\n🔗 <a href=\"https://maps.app.goo.gl/TwjvSmA6TjJuka1t8\">Google Maps</a>\n📸 <a href=\"https://www.instagram.com/drive_phangan/\">Instagram</a>\n📘 <a href=\"https://www.facebook.com/drivephangan\">Facebook</a>",

  name_invalid:
    "Ім'я повинно містити лише літери та бути не коротшим за 2 символи. Спробуйте ще раз.",
  name_save_error: "Не вдалося зберегти ім'я. Спробуйте ще раз.",
  name_saved: "Ім'я успішно збережено.",

  phone_invalid: "Невірний формат номера. Приклад: +12345678900",
  phone_save_error: "Не вдалося зберегти номер. Спробуйте ще раз.",
  phone_saved: "Номер телефону успішно збережено.",

  passport_missing: "Надішліть фото паспорта або введіть його номер.",
  passport_save_error: "Не вдалося зберегти дані паспорта. Спробуйте ще раз.",
  passport_saved: "Дані паспорта збережено.",
  passport_download_error:
    "Сталася помилка під час отримання фото. Спробуйте ще раз.",

  user_not_found: "Помилка: користувача не знайдено.",
  not_registered: "Ви не зареєстровані.",

  booking_intro:
    "🚘 <b>Оренда транспорту</b>\n\nОберіть зручний спосіб бронювання:\n- спочатку обрати <b>дати</b>, а потім доступний транспорт;\n- або спочатку обрати <b>транспорт</b>, а потім вільні дати.\n\n📌 Оберіть варіант нижче:",
  booking_btn_date_first: "📅 Спочатку обрати дату",
  booking_btn_bike_first: "🚘 Спочатку обрати транспорт",

  booking_choose_start_date: "📅 Оберіть дату початку оренди.",
  booking_choose_end_date: "📅 Оберіть дату закінчення оренди:",
  booking_choose_start_time: "⏰ Оберіть час початку оренди:",
  booking_choose_end_time: "⏰ Оберіть час закінчення оренди:",
  booking_time_invalid: "Невірний час. Оберіть зі списку.",
  booking_start_in_past: "Час початку має бути щонайменше через 1 годину від зараз.",
  booking_end_before_start: "Дата закінчення не може бути раніше початку.",
  booking_min_duration: "Мінімальна тривалість оренди — 1 година.",
  booking_choose_category: "🚘 Спочатку оберіть категорію транспорту.",
  booking_choose_bike: "🚘 Оберіть транспорт:",
  booking_no_bikes_in_category: "😔 У цій категорії поки немає транспорту.",

  booking_category_light: "🛵 Легкі (100cc-110cc)",
  booking_category_comfort: "🛵 Комфорт (150cc-160cc)",
  booking_category_maxy: "🛵 Максі (300cc-350cc)",
  category_light_label: "Легкі (100cc-110cc)",
  category_comfort_label: "Комфорт (150cc-160cc)",
  category_maxi_label: "Максі (300cc-350cc)",
  category_cars_label: "Автомобілі",
  category_scooters_label: "Скутери",

  booking_dates_not_selected: "Дати оренди не обрані.",
  booking_profile_required:
    "Для бронювання вкажіть ім'я та номер телефону в розділі «Мій профіль».",
  booking_no_available_bikes:
    "😔 На вибрані дати немає доступного транспорту.",
  booking_no_availability_lead:
    "На ці дати немає вільного транспорту. Ми створили заявку для оператора — він зв'яжеться з вами і спробує знайти варіант.",
  admin_no_availability_lead:
    "🚨 <b>Немає доступних байків</b>\n\n📅 Дати: {start} — {end}\n👤 Користувач: {user} (@{username})\n📞 Телефон: {phone}\n🏷️ Категорія: {category}\n✏️ Коментар: {comment}",
  booking_available_bikes_title: "🚘 Доступний транспорт:",

  booking_range_conflict:
    "У вибраному діапазоні вже є зайняті дати. Спробуйте ще раз.\n\n📅 Оберіть дату початку оренди:",
  booking_range_conflict_bike:
    "У вибраному діапазоні є зайняті дати для цього транспорту. Оберіть інший період.",
  booking_end_before_start: "Дата закінчення не може бути раніше початку.",
  booking_date_in_past: "Не можна вибрати дату в минулому.",
  booking_date_invalid: "Некоректна дата. Відкрийте календар знову.",

  booking_invalid_bike_id: "Невірний формат ID транспорту.",
  booking_bike_not_found: "Транспорт не знайдено.",

  booking_period_label: "Період оренди:",
  booking_price_label: "Вартість:",
  days_label: "днів",

  booking_add_to_rental_btn: "✅ Додати до оренди",

  booking_not_enough_data: "Недостатньо даних для оренди.",
  booking_current_title: "🧾 <b>Поточна оренда:</b>\n\n",
  booking_item:
    "{emoji} <b>{name}</b>\n{start} - {end} ({days} {days_label})\nВартість: {price} THB\n\n",
  booking_confirm_btn: "✅ Підтвердити бронювання",
  booking_add_bike_btn: "➕ Додати транспорт",
  booking_delete_bike_btn: "🗑️ Видалити транспорт",
  booking_reset_btn: "♻️ Скинути",
  booking_comment_btn: "💬 Побажання",
  booking_add_error: "⚠️ Сталася помилка під час збереження оренди.",
  booking_service_unavailable:
    "Сервіс бронювання тимчасово недоступний. Ваші дані збережено, повторіть дію трохи пізніше.",

  booking_confirmed:
    "✅ Вашу оренду підтверджено!\nОчікуйте підтвердження адміністратора.",
  booking_no_bookings_to_confirm: "Немає бронювань для підтвердження.",
  booking_bike_busy:
    "Транспорт \"{name}\" уже зайнятий на вибрані дати. Оберіть інший період.",
  booking_admin_missing:
    "Вибачте. Зараз у системі немає адміністратора. Скасуйте цю оренду та повторіть спробу пізніше.",
  booking_admin_new:
    "🚨 <b>Нова заявка</b>\n\n👤 {user} (@{username})\n📞 Телефон: {phone}\n🛵 Модель: <b>{bike}</b>\n📅 Період: {start} — {end}\n💰 Вартість: {price}\n🧾 Депозит: {deposit}\n🪪 Документи: {docs}\n\n🪖 Шоломи: {helmets}\n🚚 Доставка: {delivery}\n🏠 Адреса: {address}\n✏️ Побажання: {comment}",

  booking_delete_failed: "Не вдалося видалити транспорт.",
  booking_bike_removed: "🗑️ Транспорт видалено з вашої оренди.",
  booking_no_bikes_in_process: "У вас немає транспорту в процесі оренди.",
  booking_delete_prompt: "🗑️ Оберіть транспорт, який хочете видалити з оренди:",
  booking_delete_bike_item: "Видалити {name}",
  booking_reset_done: "♻️ Оренду скинуто. Ви можете почати заново.",
  booking_comment_prompt:
    "💬 Введіть ваші побажання (наприклад, «подвійний шолом», «доставка в готель»):",
  booking_comment_saved: "💬 Ваші побажання збережено.",
  booking_choose_bike_btn: "Обрати транспорт",
  booking_period_selected:
    "📅 Ви обрали період оренди:\n{start} - {end}\n\nТепер оберіть транспорт.",
  booking_start_date_selected:
    "📅 Дата початку оренди: {date}\n\nТепер оберіть дату закінчення оренди.",
  booking_add_bike_to_rental_btn: "➕ Додати транспорт до оренди",
  booking_bike_summary:
    "{emoji} <b>{name}</b>\n\n<b>Період оренди:</b> {start} - {end} ({days} {days_label})\n<b>Вартість на день:</b> {price_per_day} THB\n<b>Вартість:</b> {price} THB\n\n{desc}",
  booking_season_not_found:
    "Не вдалося визначити сезон для вибраної дати.",

  btn_back: "⬅️ Назад",
  btn_home: "🏠 В меню",
  btn_main_menu: "◀️ Головне меню",

  cal_prev: "◀️",
  cal_next: "▶️",
  cal_back: "⬅️ Назад",
  cal_blocked: "⛔",
  calendar_no_scenario: "Помилка: немає активного сценарію бронювання.",

  admin_rental_not_found: "Оренду не знайдено.",
  admin_rental_status_changed: "Заявку вже оброблено або вона має інший статус.",
  admin_status_approved: "підтверджена",
  admin_status_cancelled: "відхилена",
  admin_request_status: "Заявка #{id} {status}.",
  admin_btn_approve: "Підтвердити",
  admin_btn_cancel: "Відхилити",
  admin_docs_ok: "надані",
  admin_docs_missing: "не завантажені",
  admin_cancel_by_client:
    "🚨 <b>Скасовано клієнтом</b>\n\nID: {id}\n👤 {user} (@{username})\n📞 Телефон: {phone}\n📅 Дати: {start} — {end}",
  admin_decline_prompt:
    "Введіть причину відмови для заявки #{id}. Клієнт побачить це повідомлення.",
  admin_decline_skip_btn: "Відхилити без причини",
  admin_decline_done: "Заявку #{id} відхилено. Причина: {reason}",

  user_rental_declined:
    "❌ Вашу заявку #{id} відхилено.\nПричина: {reason}\nЯкщо є питання — напишіть у підтримку.",
  user_decline_reason_default: "Причина не вказана.",

  user_no_name: "(без імені)",
  user_default_name: "користувач",

  start_registration: "Почнімо з імені.",
  skip_registration: "Реєстрацію можна пройти пізніше.",
  skip_registration_reply: "Добре. Якщо передумаєте — надішліть /start знову.",

  booking_options_title:
    "⚙️ Опції оренди:\n• Час початку: {start_time}\n• Час повернення: {end_time}\n• Шоломи: {helmets}\n• Доставка: {delivery}\n• Адреса доставки: {address}\n• Побажання: {notes}",
  booking_options_btn: "⚙️ Опції",
  booking_options_delivery_on: "увімкнено",
  booking_options_delivery_off: "немає",
  booking_options_no_address: "не вказана",
  booking_options_no_notes: "не вказані",
  booking_options_time_not_set: "не вказано",
  booking_options_helmets_inc: "➕ Шолом",
  booking_options_helmets_dec: "➖ Шолом",
  booking_options_toggle_delivery: "🚚 Доставка так/ні",
  booking_options_set_address: "🏠 Адреса доставки",
  booking_options_set_notes: "✏️ Побажання",
  booking_options_time_start: "🕘 Час початку",
  booking_options_time_end: "🕘 Час повернення",
  booking_options_back: "⬅️ Назад",
  booking_options_saved: "Опції оновлено.",
  booking_options_address_prompt: "🏠 Введіть адресу доставки:",
  booking_options_notes_prompt: "✏️ Введіть ваші побажання/коментар:",
  booking_options_address_saved: "Адресу доставки збережено.",
  booking_delivery_address_required: "Перед підтвердженням бронювання вкажіть адресу доставки.",
  booking_options_notes_saved: "Побажання збережено.",
  admin_not_allowed: "Доступ заборонено.",
  admin_menu_title: "👑 Адмін-панель",
  admin_menu_active_btn: "🟢 Активні заявки",
  admin_menu_pending_btn: "⏳ Непідтверджені",
  admin_menu_confirmed_btn: "✅ Підтверджені",
  admin_list_title_active: "Активні заявки",
  admin_list_title_pending: "Непідтверджені заявки",
  admin_list_title_confirmed: "Підтверджені заявки",
  admin_list_empty: "Заявок немає.",
  admin_list_client: "Клієнт",
  admin_list_phone: "Телефон",
  admin_list_dates: "Дати",
  admin_list_status: "Статус",
  admin_deposit_btn: "💸 Депозит",
  admin_deposit_prompt: "Введіть текст депозиту для броні #{id}:",
  admin_deposit_saved: "Депозит оновлено для броні #{id}.",
  rent_deposit_title: "💸 Депозит та оплата",
  rent_deposit_empty: "Немає активних бронювань для депозиту.",
  rent_deposit_required_label: "Депозит",
  rent_deposit_status_label: "Статус",
  rent_deposit_status_paid: "сплачено",
  rent_deposit_status_unpaid: "не сплачено",
  rent_deposit_note_label: "Коментар",
  admin_menu_bikes_btn: "🛵 Байки",
  admin_bikes_menu_title: "🛵 Керування байками",
  admin_bikes_add_btn: "➕ Додати байк",
  admin_bikes_edit_btn: "✏️ Редагувати байк",
  admin_bikes_list_title: "Оберіть байк:",
  admin_bikes_empty: "Байків поки немає.",
  admin_bike_edit_title: "Керування байком",
  admin_bike_label_name: "Назва",
  admin_bike_label_status: "Статус",
  admin_bike_status_active: "активний",
  admin_bike_status_inactive: "неактивний",
  admin_bike_edit_name_btn: "Назва",
  admin_bike_edit_desc_btn: "Опис",
  admin_bike_edit_emoji_btn: "Емодзі",
  admin_bike_edit_category_btn: "Категорія",
  admin_bike_edit_prices_btn: "Ціни за коефіцієнтами",
  admin_bike_copy_prices_btn: "Скопіювати ціни",
  admin_bike_deactivate_btn: "Деактивувати",
  admin_bike_activate_btn: "Активувати",
  admin_bike_prompt_name: "Введіть назву байка:",
  admin_bike_prompt_description: "Введіть опис (або '-' щоб пропустити):",
  admin_bike_prompt_emoji: "Введіть емодзі (або '-' щоб пропустити):",
  admin_bike_prompt_category: "Оберіть категорію:",
  admin_bike_prompt_bike_id: "Введіть bike_id (або '-' для авто):",
  admin_bike_prompt_pricing_method: "Оберіть спосіб задання цін:",
  admin_bike_pricing_method_coeff: "Коефіцієнти",
  admin_bike_pricing_method_copy: "Скопіювати ціни з байка",
  admin_bike_prompt_profile: "Оберіть профіль коефіцієнтів:",
  admin_bike_profile_not_found: "Профіль не знайдено.",
  admin_bike_prompt_base_prices: "Введіть ціни за 1 день для High, Middle, Low (приклад: 1200 1000 900):",
  admin_bike_invalid_price_input: "Не вдалося розпізнати ціни. Введіть 3 числа.",
  admin_bike_price_preview_title: "Попередній перегляд цін",
  admin_bike_price_profile: "Профіль",
  admin_bike_price_rounding: "Округлення",
  admin_bike_price_base: "База (High/Middle/Low)",
  admin_bike_confirm_btn: "✅ Підтвердити",
  admin_bike_cancel_btn: "Скасувати",
  admin_bike_confirm_failed: "Не вдалося підтвердити дію.",
  admin_bike_cancelled: "Дію скасовано.",
  admin_bike_created: "Байк створено.",
  admin_bike_updated: "Байк оновлено.",
  admin_bike_not_found: "Байк не знайдено.",
  admin_bike_missing_data: "Недостатньо даних для збереження.",
  admin_bike_copy_from_label: "Скопіювати ціни з",
};
