module.exports = {
  lang_prompt: "🌍 Оберіть мову / Choose your language / Выберите язык",
  lang_saved: "✅ Language saved.",
  lang_unsupported: "Unsupported language.",
  lang_save_error: "Failed to save language. Please try again later.",

  cmd_start: "🏠 Main menu",
  cmd_menu: "📋 Open menu",
  cmd_book: "📅 Start booking",
  cmd_language: "🌍 Change language",
  cmd_admin: "👑 Admin panel",

  welcome_new:
    "👋 Welcome, {name}!\n\nTo continue, please complete a short registration.",
  welcome_back: "👋 Welcome back, {name}!",

  enter_name: "✏️ Please enter your name:",
  enter_phone:
    "📞 Please enter your phone number in international format (e.g. +79995551234):",
  enter_passport: "🪪 Please send a passport photo or enter the passport number:",

  update_name_prompt: "✏️ Enter a new name:",
  update_tel_prompt:
    "📞 Enter a phone number or share contact (button below):",
  update_passport_prompt:
    "🆔 Send a passport photo or enter the passport number:",
  share_contact_btn: "📨 Share contact",

  menu_title: "🏠 Main menu:",
  menu_my_rent: "🛵 My Rent",
  menu_support: "💬 Support",
  menu_prices: "💸 Look Prices",
  menu_account: "👤 My Account",
  menu_conditions: "📝 Rent Conditions",
  menu_about: "ℹ️ About Us",
  menu_book: "📅 Book a bike",
  menu_rental: "🧾 My rental",
  menu_update_name: "✏️ Update name",
  menu_update_tel: "📞 Update phone",
  menu_update_passport: "🪪 Upload passport",

  support_info:
    "💬 Support.\nSend your question here and we'll reply as soon as possible.",
  prices_info:
    "💸 Prices are shown for each bike when you pick dates.\nTap “My Rent” to choose dates and see totals.",
  prices_choose_season:
    "Choose a season:\n\n🔺 High season (December, January, February, March)\n🟠 Mid season (April, May, October, November)\n🔻 Low season (June, July, August, September)",
  prices_season_high: "🔺 High season",
  prices_season_middle: "🟠 Mid season",
  prices_season_low: "🔻 Low season",
  prices_image_missing:
    "Couldn't load the price list. Please try again.",
  prices_loading: "Loading price list…",
  account_info:
    "👤 Add your booking details here. Choose what you want to update:",
  account_profile_title: "👤 My Profile",
  account_name_label: "Name",
  account_phone_label: "Phone",
  account_passport_label: "Passport",
  account_passport_photo: "Photo uploaded",
  account_passport_missing: "Not provided",
  account_value_missing: "Not set",
  account_passport_number_value: "Number: {number}",
  account_profile_hint: "Choose what you want to update:",
  conditions_info:
    "🆔 Documents\nRequired:\n• Photo of international passport\n• Driver’s license (international preferred)\n• Age 18+\nSigning the rental agreement is mandatory.\n\n💰 Deposit & payment\nDeposit:\n• Passport or cash deposit\n• Amount depends on model:\n▫️ Standard bikes — $100–$300\n▫️ Powerful bikes (300–350cc) — from $400 and above\n\nPayment:\n• Cash or online\n• All terms are discussed in advance — no hidden fees\n\nEarly return:\nIf you plan to return earlier, please note:\n• Daily rental — return less than 3 days before end is not refunded\n• Monthly rental — return less than 7 days before end is also not recalculated\n• Other cases: possible recalculation by agreement\n\n🛵 Damage & responsibility\nWe take photos/video of the bike before rental.\nIf damaged:\n• Payment at real cost of original parts and labor\n• Rarely, downtime for repair may be considered\nInsurance doesn’t cover scooters.\nPunctured tire: tenant fixes it (usually 100–200 THB nearby).\nIf battery drained due to lights left on — service fee 100–400 THB, depending on location.\n\n⏱ Return & extension\nRental is per 24h — return at the same time you received the bike.\nIf you want to extend, warn us in advance (ideally a few days).\nIn high season bikes are often booked day-to-day — we must honor other bookings.\nHalf-day extension (e.g., noon to evening) — possible by agreement, usually ~50% of day price.\n\n📍 Pickup\nPickup on Bantai.\nDelivery:\n• Around the island — 100–400 THB (distance-based)\n• Thong Sala pier — 150 THB\n• Within Bantai — free",
  conditions_accept_btn: "✅ Accept rental terms",
  conditions_accepted_label: "✅ Terms accepted",
  conditions_book_btn: "📅 Book now",
  conditions_view_btn: "📄 Rental terms",
  conditions_accept_required:
    "To confirm your booking, please accept the rental terms. Tap “Accept rental terms”.",
  conditions_terms_link:
    "Full user agreement: <a href=\"https://example.com/terms\">https://example.com/terms</a>",

  booking_price_tbd: "price to be confirmed",

  rent_intro: "Let's find your perfect scooter. Choose an option:",
  rent_btn_book: "🛵 Book now",
  rent_btn_current: "🗂 Current bookings",
  rent_btn_history: "📜 Rental history",
  rent_btn_contract: "📄 Rental agreement",
  rent_btn_payment: "💰 Deposit/Payment",
  rent_btn_settings: "⚙️ Settings",
  rent_btn_support: "💬 Support",
  rent_btn_confirm: "✅ Confirm booking",
  rent_current_empty: "You have no active or pending bookings.",
  rent_current_title: "📌 Your current bookings",
  rent_current_draft_title: "📝 Draft booking",
  rent_current_draft_hint:
    "You can continue the booking now or come back to it later.",
  rent_current_draft_continue_btn: "Continue booking",
  rent_current_back_btn: "⬅️ Back to current bookings",
  rent_current_actions_title: "⚙️ Draft management",
  rent_current_actions_hint:
    "Add bikes, leave notes, or confirm before sending to the admin.",
  rent_history_empty: "History is empty.",
  rent_details_title: "📍 Booking details",
  rent_details_status: "Status: {status}",
  rent_status_process: "in progress",
  rent_status_pending: "awaiting confirmation",
  rent_status_active: "active",
  rent_status_ready: "ready for pickup",
  rent_status_cancelled_by_client: "cancelled by client",
  rent_status_cancelled: "cancelled",
  rent_status_completed: "completed",
  rent_status_approved: "approved",
  reminder_start_24h: "Reminder: rental starts in 24 hours",
  reminder_start_1h: "Reminder: rental starts in 1 hour",
  reminder_end_24h: "Reminder: rental ends in 24 hours",
  reminder_end_1h: "Reminder: rental ends in 1 hour",
  reminder_model_label: "Model",
  reminder_period_label: "Period",
  reminder_status_label: "Status",
  reminder_view_current_btn: "Current bookings",
  reminder_view_details_btn: "Booking details",
  user_rental_approved:
    "Your booking #{id} has been approved ✅\nModel: {model}\nDates: {start} — {end}\nStatus: {status}\nYou can view details in My Rent.",
  rent_view_details_btn: "View booking",
  rent_details_dates: "Dates: {start} - {end}",
  rent_details_model: "Model: {model}",
  rent_details_unit: "Unit: {unit}",
  rent_details_helmets: "Helmets: {helmets}",
  rent_details_delivery: "Delivery: {delivery}",
  rent_details_address: "Address: {address}",
  rent_details_notes: "Notes: {notes}",
  rent_details_price: "Total: {price} THB",
  rent_details_deposit: "Deposit: {deposit} THB",
  rent_details_contract: "Contract: {contract}",
  rent_action_details: "📍 Details",
  rent_action_edit: "✏️ Edit",
  rent_action_cancel: "❌ Cancel",
  rent_action_back: "◀️ Back",
  rent_cancel_confirm: "Cancel booking ID {id}?",
  rent_cancelled: "Booking cancelled.",
  rent_cannot_cancel: "You cannot cancel this booking.",
  rent_history_details: "📍 Details (history)",
  about_info:
    "🏝️ DRIVE PHANGAN — scooter and car rental on Koh Phangan.\nOfficially operating since 2019.\n🛵 Every year we update our fleet with new models — for those who value comfort, style, and freedom.\n\n🚀 Renting with us is honest and transparent — no shady tricks or scratch scams.\n⭐ Over 100 positive reviews on Google Maps and many returning customers season after season.\nReliable, simple, and with care for your perfect vacation ✨\n\n🤖 This bot is made to keep booking quick and effortless — everything is automated. You can complete all steps right here. If you have any questions, we are always online!\n\n📍 Find us easily:\n🔗 <a href=\"https://maps.app.goo.gl/TwjvSmA6TjJuka1t8\">Google Maps</a>\n📸 <a href=\"https://www.instagram.com/drive_phangan/\">Instagram</a>\n📘 <a href=\"https://www.facebook.com/drivephangan\">Facebook</a>",
  support_info:
    "💬 Support.\nIf you have questions, choose a convenient contact option below.",
  support_btn_call: "📞 Call us",
  support_btn_faq: "📄 FAQ",
  support_btn_find: "📍 How to find us",
  support_btn_admin: "💬 Message admin",
  support_call_text:
    "📞 Phone: +66 97 181 9946\n💬 WhatsApp: +66 97 181 9946\n\nTap the button below to open a WhatsApp chat.",
  support_call_whatsapp_btn: "💬 Chat on WhatsApp",
  support_faq_text:
    "📄 FAQ\n\n• How to book? — Pick dates and a bike in the bot, then confirm.\n• What docs are needed? — Passport photo.\n• Helmets? — Yes, on request.\n• Delivery? — Available, add your address in comments.\n• Payment? — We’ll confirm it after booking.",
  support_find_text:
    "📍 Address: Koh Phangan, Thailand\n\nFind us easily:\n🔗 <a href=\"https://maps.app.goo.gl/TwjvSmA6TjJuka1t8\">Google Maps</a>\n📸 <a href=\"https://www.instagram.com/drive_phangan/\">Instagram</a>\n📘 <a href=\"https://www.facebook.com/drivephangan\">Facebook</a>",

  name_invalid:
    "Name must contain only letters and be at least 2 characters long. Try again.",
  name_save_error: "Failed to save name. Try again.",
  name_saved: "Name saved successfully.",

  phone_invalid: "Invalid phone format. Example: +12345678900",
  phone_save_error: "Failed to save phone. Try again.",
  phone_saved: "Phone saved successfully.",

  passport_missing: "Send a passport photo or enter the passport number.",
  passport_save_error: "Failed to save passport data. Try again.",
  passport_saved: "Passport data saved successfully.",
  passport_download_error:
    "An error occurred while downloading the photo. Try again.",

  user_not_found: "Error: user not found.",
  not_registered: "You are not registered.",

  booking_intro:
    "🚲 <b>Bike rental</b>\n\nChoose a convenient booking method:\n- first choose <b>dates</b>, then available bikes;\n- or first choose a <b>bike</b>, then available dates.\n\n📌 Choose an option below:",
  booking_btn_date_first: "📅 Choose date first",
  booking_btn_bike_first: "🏍️ Choose bike first",

  booking_choose_start_date: "📅 Choose the rental start date.",
  booking_choose_end_date: "📅 Choose the rental end date:",
  booking_choose_start_time: "⏰ Choose start time:",
  booking_choose_end_time: "⏰ Choose end time:",
  booking_time_invalid: "Invalid time. Choose from the list.",
  booking_start_in_past: "Start time must be at least 1 hour from now.",
  booking_end_before_start: "End date cannot be earlier than start date.",
  booking_min_duration: "Minimum rental duration is 1 hour.",
  booking_choose_category: "🏍️ First choose a bike category.",
  booking_choose_bike: "🏍️ Choose a bike:",
  booking_no_bikes_in_category: "😔 No bikes in this category yet.",

  booking_category_light: "🌿 Light (110-125cc)",
  booking_category_comfort: "✨ Comfort (150-160cc)",
  booking_category_maxy: "🏎️ Maxy (300-350cc)",

  booking_dates_not_selected: "Rental dates are not selected.",
  booking_profile_required:
    "To book, please provide your name and phone number in My Account.",
  booking_no_available_bikes:
    "😔 Unfortunately, no bikes are available for the selected dates.",
  booking_no_availability_lead:
    "No bikes are free for these dates. We created a request for the operator — they will contact you and try to find an option.",
  admin_no_availability_lead:
    "🚨 <b>No availability</b>\n\n📅 Dates: {start} — {end}\n👤 User: {user} (@{username})\n📞 Phone: {phone}\n🏷️ Category: {category}\n✏️ Comment: {comment}",
  booking_available_bikes_title: "🏍️ Available bikes:",

  booking_range_conflict:
    "There are already booked dates in the selected range. Try again.\n\n📅 Choose the rental start date:",
  booking_range_conflict_bike:
    "The selected range includes booked dates for this bike. Choose another period.",
  booking_end_before_start: "End date cannot be earlier than start date.",
  booking_date_in_past: "You cannot select a date in the past.",

  booking_invalid_bike_id: "Invalid bike ID format.",
  booking_bike_not_found: "Bike not found.",
  booking_season_not_found: "Failed to determine season for the selected date.",

  booking_period_label: "Rental period:",
  booking_price_label: "Price:",
  days_label: "days",

  booking_add_to_rental_btn: "✅ Add to rental",

  booking_not_enough_data: "Not enough data to create a rental.",
  booking_current_title: "🧾 <b>Current rental:</b>\n\n",
  booking_item:
    "🏍️ <b>{name}</b>\n{start} - {end} ({days} {days_label})\nPrice: {price} THB\n\n",
  booking_confirm_btn: "✅ Confirm booking",
  booking_add_bike_btn: "➕ Add bike",
  booking_delete_bike_btn: "🗑️ Remove bike",
  booking_reset_btn: "♻️ Reset",
  booking_comment_btn: "💬 Notes",
  booking_add_error: "⚠️ Error while saving the rental.",

  booking_confirmed:
    "✅ Your rental is confirmed!\nPlease wait for admin confirmation.",
  booking_no_bookings_to_confirm: "No bookings to confirm.",
  booking_bike_busy:
    'Bike "{name}" is already booked for these dates. Please choose another period.',
  booking_admin_missing:
    "Sorry. There is no admin in the system right now. Please cancel this rental and try again later.",
  booking_admin_new:
    "🚨 <b>New booking request</b>\n\n👤 {user} (@{username})\n📞 Phone: {phone}\n🛵 Model: <b>{bike}</b>\n📅 Period: {start} — {end}\n💰 Price: {price}\n🧾 Deposit: {deposit}\n🪪 Documents: {docs}\n\n🪖 Helmets: {helmets}\n🚚 Delivery: {delivery}\n🏠 Address: {address}\n✏️ Notes: {comment}",

  booking_delete_failed: "Failed to remove the bike.",
  booking_bike_removed: "🗑️ Bike removed from your rental.",
  booking_no_bikes_in_process: "You have no bikes in the rental process.",
  booking_delete_prompt: "🗑️ Choose a bike to remove from your rental:",
  booking_delete_bike_item: "Remove {name}",
  booking_reset_done: "♻️ Rental reset. You can start again.",
  booking_comment_prompt:
    "💬 Enter your notes (e.g. “double helmet”, “hotel delivery”):",
  booking_comment_saved: "💬 Your notes have been saved.",
  booking_choose_bike_btn: "Choose a bike",
  booking_period_selected:
    "📅 You selected the rental period:\n{start} - {end}\n\nNow choose a bike.",
  booking_start_date_selected:
    "📅 Start date: {date}\n\nNow choose the end date.",
  booking_add_bike_to_rental_btn: "➕ Add a bike to the rental",
  booking_bike_summary:
    "🛵 <b>{name}</b>\n\n<b>Rental period:</b> {start} - {end} ({days} {days_label})\n<b>Price per day:</b> {price_per_day} THB\n<b>Price:</b> {price} THB\n\n{desc}",

  btn_back: "⬅️ Back",
  btn_home: "🏠 Home",
  btn_main_menu: "◀️ Main menu",

  cal_prev: "◀️",
  cal_next: "▶️",
  cal_back: "⬅️ Back",
  cal_blocked: "⛔",
  calendar_no_scenario: "Error: no active booking flow.",

  admin_rental_not_found: "Rental not found.",
  admin_status_approved: "approved",
  admin_status_cancelled: "cancelled",
  admin_request_status: "Request #{id} {status}.",
  admin_btn_approve: "Approve",
  admin_btn_cancel: "Reject",
  admin_docs_ok: "provided",
  admin_docs_missing: "missing",
  admin_cancel_by_client:
    "🚨 <b>Cancelled by client</b>\n\nID: {id}\n👤 {user} (@{username})\n📞 Phone: {phone}\n📅 Dates: {start} — {end}",
  admin_decline_prompt:
    "Please type a rejection reason for booking #{id}. The client will see this.",
  admin_decline_skip_btn: "Reject without reason",
  admin_decline_done: "Booking #{id} rejected. Reason: {reason}",

  user_rental_declined:
    "❌ Your booking #{id} was rejected.\nReason: {reason}\nIf you have questions, please contact support.",
  user_decline_reason_default: "Reason not provided.",

  user_no_name: "(no name)",
  user_default_name: "user",

  start_registration: "Let's start with your name.",
  skip_registration: "You can complete registration later.",
  skip_registration_reply: "Okay. If you change your mind, send /start again.",

  booking_options_title:
    "⚙️ Options:\n• Start time: {start_time}\n• End time: {end_time}\n• Helmets: {helmets}\n• Delivery: {delivery}\n• Delivery address: {address}\n• Notes: {notes}",
  booking_options_btn: "⚙️ Options",
  booking_options_delivery_on: "on",
  booking_options_delivery_off: "off",
  booking_options_no_address: "not set",
  booking_options_no_notes: "not set",
  booking_options_time_not_set: "not set",
  booking_options_helmets_inc: "➕ Helmet",
  booking_options_helmets_dec: "➖ Helmet",
  booking_options_toggle_delivery: "🚚 Delivery on/off",
  booking_options_set_address: "🏠 Delivery address",
  booking_options_set_notes: "✏️ Notes",
  booking_options_time_start: "🕘 Start time",
  booking_options_time_end: "🕘 End time",
  booking_options_back: "⬅️ Back",
  booking_options_saved: "Options updated.",
  booking_options_address_prompt: "🏠 Enter delivery address:",
  booking_options_notes_prompt: "✏️ Enter your notes:",
  booking_options_address_saved: "Delivery address saved.",
  booking_options_notes_saved: "Notes saved.",
  admin_not_allowed: "Access denied.",
  admin_menu_title: "👑 Admin panel",
  admin_menu_active_btn: "🟢 Active requests",
  admin_menu_pending_btn: "⏳ Unconfirmed",
  admin_menu_confirmed_btn: "✅ Confirmed",
  admin_list_title_active: "Active requests",
  admin_list_title_pending: "Unconfirmed requests",
  admin_list_title_confirmed: "Confirmed requests",
  admin_list_empty: "No requests found.",
  admin_list_client: "Client",
  admin_list_phone: "Phone",
  admin_list_dates: "Dates",
  admin_list_status: "Status",
  admin_deposit_btn: "💸 Deposit",
  admin_deposit_prompt: "Enter deposit text for booking #{id}:",
  admin_deposit_saved: "Deposit updated for booking #{id}.",
  rent_deposit_title: "💸 Deposit and payment",
  rent_deposit_empty: "No active bookings for deposit info.",
  rent_deposit_required_label: "Deposit",
  rent_deposit_status_label: "Status",
  rent_deposit_status_paid: "paid",
  rent_deposit_status_unpaid: "not paid",
  rent_deposit_note_label: "Note",
  admin_menu_bikes_btn: "🛵 Bikes",
  admin_bikes_menu_title: "🛵 Bike management",
  admin_bikes_add_btn: "➕ Add bike",
  admin_bikes_edit_btn: "✏️ Edit bike",
  admin_bikes_list_title: "Select a bike:",
  admin_bikes_empty: "No bikes yet.",
  admin_bike_edit_title: "Bike management",
  admin_bike_label_name: "Name",
  admin_bike_label_status: "Status",
  admin_bike_status_active: "active",
  admin_bike_status_inactive: "inactive",
  admin_bike_edit_name_btn: "Name",
  admin_bike_edit_desc_btn: "Description",
  admin_bike_edit_emoji_btn: "Emoji",
  admin_bike_edit_category_btn: "Category",
  admin_bike_edit_prices_btn: "Prices by coefficients",
  admin_bike_copy_prices_btn: "Copy prices",
  admin_bike_deactivate_btn: "Deactivate",
  admin_bike_activate_btn: "Activate",
  admin_bike_prompt_name: "Enter bike name:",
  admin_bike_prompt_description: "Enter description (or '-' to skip):",
  admin_bike_prompt_emoji: "Enter emoji (or '-' to skip):",
  admin_bike_prompt_category: "Choose category:",
  admin_bike_prompt_bike_id: "Enter bike_id (or '-' for auto):",
  admin_bike_prompt_pricing_method: "Choose pricing method:",
  admin_bike_pricing_method_coeff: "Coefficients",
  admin_bike_pricing_method_copy: "Copy prices from bike",
  admin_bike_prompt_profile: "Choose coefficient profile:",
  admin_bike_profile_not_found: "Profile not found.",
  admin_bike_prompt_base_prices: "Enter 1-day prices for High, Middle, Low (e.g. 1200 1000 900):",
  admin_bike_invalid_price_input: "Could not parse prices. Enter 3 numbers.",
  admin_bike_price_preview_title: "Price preview",
  admin_bike_price_profile: "Profile",
  admin_bike_price_rounding: "Rounding",
  admin_bike_price_base: "Base (High/Middle/Low)",
  admin_bike_confirm_btn: "✅ Confirm",
  admin_bike_cancel_btn: "Cancel",
  admin_bike_confirm_failed: "Failed to confirm action.",
  admin_bike_cancelled: "Action cancelled.",
  admin_bike_created: "Bike created.",
  admin_bike_updated: "Bike updated.",
  admin_bike_not_found: "Bike not found.",
  admin_bike_missing_data: "Not enough data to save.",
  admin_bike_copy_from_label: "Copy prices from",
};
