const RENTAL_STATUS = Object.freeze({
  PROCESS: "process",
  PENDING: "pending",
  APPROVED: "approved",
  ACTIVE: "active",
  READY: "ready",
  COMPLETED: "completed",
  FINISHED: "finished",
  EXPIRED: "expired",
  RETURNED: "returned",
  CANCELLED: "cancelled",
  CANCELLED_BY_CLIENT: "cancelled_by_client",
});

const DRAFT_RENTAL_STATUSES = [RENTAL_STATUS.PROCESS];

const BLOCKING_RENTAL_STATUSES = [
  RENTAL_STATUS.PENDING,
  RENTAL_STATUS.APPROVED,
  RENTAL_STATUS.ACTIVE,
  RENTAL_STATUS.READY,
];

const CURRENT_RENTAL_STATUSES = [
  RENTAL_STATUS.PROCESS,
  RENTAL_STATUS.PENDING,
  RENTAL_STATUS.APPROVED,
  RENTAL_STATUS.ACTIVE,
  RENTAL_STATUS.READY,
];

const HISTORY_RENTAL_STATUSES = [
  RENTAL_STATUS.CANCELLED,
  RENTAL_STATUS.CANCELLED_BY_CLIENT,
  RENTAL_STATUS.COMPLETED,
  RENTAL_STATUS.FINISHED,
  RENTAL_STATUS.EXPIRED,
  RENTAL_STATUS.RETURNED,
];

const USER_CANCELLABLE_RENTAL_STATUSES = [
  RENTAL_STATUS.PROCESS,
  RENTAL_STATUS.PENDING,
  RENTAL_STATUS.APPROVED,
  RENTAL_STATUS.ACTIVE,
  RENTAL_STATUS.READY,
];

const ADMIN_CANCELLABLE_RENTAL_STATUSES = [
  RENTAL_STATUS.PENDING,
  RENTAL_STATUS.APPROVED,
  RENTAL_STATUS.ACTIVE,
  RENTAL_STATUS.READY,
];

const ADMIN_APPROVABLE_RENTAL_STATUSES = [RENTAL_STATUS.PENDING];

const ADMIN_LIST_STATUSES = {
  active: BLOCKING_RENTAL_STATUSES,
  pending: [RENTAL_STATUS.PENDING],
  confirmed: [RENTAL_STATUS.APPROVED, RENTAL_STATUS.ACTIVE, RENTAL_STATUS.READY],
};

const CALENDAR_RENTAL_STATUSES = [
  RENTAL_STATUS.PENDING,
  RENTAL_STATUS.APPROVED,
  RENTAL_STATUS.ACTIVE,
  RENTAL_STATUS.READY,
  RENTAL_STATUS.COMPLETED,
];

const KNOWN_RENTAL_STATUSES = [
  ...new Set([
    ...DRAFT_RENTAL_STATUSES,
    ...BLOCKING_RENTAL_STATUSES,
    ...HISTORY_RENTAL_STATUSES,
  ]),
];

function isKnownRentalStatus(status) {
  return KNOWN_RENTAL_STATUSES.includes(status);
}

function isBlockingRentalStatus(status) {
  return BLOCKING_RENTAL_STATUSES.includes(status);
}

module.exports = {
  RENTAL_STATUS,
  DRAFT_RENTAL_STATUSES,
  BLOCKING_RENTAL_STATUSES,
  CURRENT_RENTAL_STATUSES,
  HISTORY_RENTAL_STATUSES,
  USER_CANCELLABLE_RENTAL_STATUSES,
  ADMIN_CANCELLABLE_RENTAL_STATUSES,
  ADMIN_APPROVABLE_RENTAL_STATUSES,
  ADMIN_LIST_STATUSES,
  CALENDAR_RENTAL_STATUSES,
  KNOWN_RENTAL_STATUSES,
  isKnownRentalStatus,
  isBlockingRentalStatus,
};
